version: "3.8"

services:
  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - pgdb
      - redis

  celery:
    build: .
    container_name: celery
    command: celery -A licenta_calitatea_aerului worker -l INFO
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    volumes:
      - .:/usr/src/app
    depends_on:
      - django
      - redis

  celery-beat:
    build: .
    container_name: celery-beat
    command: celery -A licenta_calitatea_aerului beat -l INFO
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost
    depends_on:
      - django
      - redis
    volumes:
      - .:/usr/src/app

  flower:
    build: .
    container_name: flower
    command: celery -A licenta_calitatea_aerului flower
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost
    depends_on:
      - django
      - redis
    ports:
      - 5555:5555
    volumes:
      - .:/usr/src/app

  pgdb:
    image: postgres
    container_name: pgdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: "redis:alpine"

volumes:
  pgdata:
