# Generated by Django 4.1.7 on 2024-03-05 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevelcoDevice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('device_id', models.IntegerField(null=True)),
                ('eui', models.CharField(max_length=200)),
                ('manufacturer_name', models.CharField(max_length=200)),
                ('model_identifier', models.CharField(max_length=200)),
                ('default_name', models.CharField(max_length=200)),
                ('template_hash', models.CharField(max_length=200)),
                ('discovered', models.BooleanField()),
                ('online', models.BooleanField()),
                ('config_complete_pct', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MetadataDataGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('placement', models.IntegerField()),
                ('ldev_key', models.CharField(max_length=200)),
                ('dp_key', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NamingSchemaField',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('placeholder', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NamingSchema',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('use_locale', models.BooleanField()),
                ('separator', models.CharField(max_length=200)),
                ('fields', models.ManyToManyField(to='air_quality_api.namingschemafield')),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img_url', models.CharField(max_length=200)),
                ('data_groups', models.ManyToManyField(to='air_quality_api.metadatadatagroup')),
                ('naming_schema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='air_quality_api.namingschema')),
            ],
        ),
        migrations.CreateModel(
            name='DevelcoDeviceData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=200)),
                ('access', models.CharField(max_length=200)),
                ('last_updated', models.DateTimeField()),
                ('value', models.FloatField()),
                ('develco_device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='air_quality_api.develcodevice')),
            ],
        ),
        migrations.AddField(
            model_name='develcodevice',
            name='device_data',
            field=models.ManyToManyField(to='air_quality_api.develcodevicedata'),
        ),
        migrations.AddField(
            model_name='develcodevice',
            name='metadata',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='air_quality_api.metadata'),
        ),
    ]
