# Generated by Django 4.1.7 on 2023-03-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_quality_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphvalue',
            name='value',
            field=models.CharField(max_length=200),
        ),
    ]
