# Generated by Django 4.1.7 on 2024-03-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_quality_api', '0002_remove_develcodevice_device_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='develcodevicedata',
            name='value',
            field=models.CharField(max_length=200),
        ),
    ]
