# Generated by Django 4.1.7 on 2023-11-02 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('air_quality_api', '0003_develcodevicedata_metadatadatagroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='naming_schema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='air_quality_api.namingschema'),
        ),
    ]
