# Generated by Django 4.1.7 on 2024-06-05 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('air_quality_api', '0004_deviceimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomatedDevice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('endpoint', models.CharField(max_length=200)),
                ('enabled', models.BooleanField()),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='air_quality_api.deviceimages')),
            ],
        ),
    ]
