# Generated by Django 4.1.7 on 2023-11-02 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('air_quality_api', '0004_alter_metadata_naming_schema'),
    ]

    operations = [
        migrations.RenameField(
            model_name='develcodevice',
            old_name='manufacturer',
            new_name='manufacturer_name',
        ),
        migrations.AlterField(
            model_name='metadata',
            name='naming_schema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='air_quality_api.namingschema'),
        ),
    ]
