# Generated by Django 4.1.7 on 2024-06-05 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('air_quality_api', '0005_automateddevice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automateddevice',
            name='image',
        ),
        migrations.AddField(
            model_name='deviceimages',
            name='automated_device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='air_quality_api.automateddevice'),
        ),
    ]
