# Generated by Django 4.1.7 on 2024-06-05 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('air_quality_api', '0006_remove_automateddevice_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('image_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='DeviceImages',
        ),
        migrations.AddField(
            model_name='automateddevice',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='air_quality_api.deviceimage'),
        ),
    ]
