# Generated by Django 4.1.7 on 2023-11-02 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('air_quality_api', '0006_alter_develcodevice_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='develcodevice',
            name='metadata',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='air_quality_api.metadata'),
        ),
    ]
