# Generated by Django 4.1.7 on 2024-06-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("air_quality_api", "0007_deviceimage_delete_deviceimages_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Limits",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("low_value", models.IntegerField()),
                ("high_value", models.IntegerField()),
                ("unit", models.CharField(max_length=200)),
            ],
        ),
        # insert in the database the limits
        migrations.RunSQL(
            "INSERT INTO air_quality_api_limits (name, low_value, high_value, unit) VALUES ('VOC', 0, 400, 'ppm');"
            "INSERT INTO air_quality_api_limits (name, low_value, high_value, unit) VALUES ('Temperature', 19, 22, '°C');"
            "INSERT INTO air_quality_api_limits (name, low_value, high_value, unit) VALUES ('Humidity', 40, 60, '% RH³');"
        ),
    ]
