# Generated by Django 4.1.7 on 2024-06-15 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('air_quality_api', '0008_limits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='develcodevicedata',
            name='develco_device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_data', to='air_quality_api.develcodevice'),
        ),
    ]
