# Generated by Django 4.1.7 on 2024-06-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("air_quality_api", "0009_alter_develcodevicedata_develco_device"),
    ]

    operations = [
        migrations.AddField(
            model_name="limits",
            name="image_url",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.RunSQL(
            "UPDATE air_quality_api_limits SET image_url = 'https://cdn-icons-png.flaticon.com/512/12015/12015825.png' WHERE name = 'VOC';"
            "UPDATE air_quality_api_limits SET image_url = 'https://cdn-icons-png.flaticon.com/512/3653/3653556.png' WHERE name = 'Temperature';"
            "UPDATE air_quality_api_limits SET image_url = 'https://cdn-icons-png.flaticon.com/512/15468/15468611.png' WHERE name = 'Humidity';"
        ),
    ]
