# Generated by Django 4.1.7 on 2024-06-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("air_quality_api", "0010_limits_image_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="IsAutomaticModeActive",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("is_active", models.BooleanField()),
            ],
        ),
        migrations.RunSQL(
            "INSERT INTO air_quality_api_isautomaticmodeactive (is_active) VALUES (TRUE);"
        ),
    ]
